name: Build and Release Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change directory
        run: cd rustsqlite && ls -la

      - name: Build binary
        run: cd rustsqlite && cargo build --release
      
      - name: Debug binary file path
        run: ls -la target/release/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rustsqlite
          path: target/release/rustsqlite